### ISSUE TITLE
Inconsistent variable naming in plotting functions

### ISSUE THREAD

**Issue by Wartynas** [HorridTom/hospitalflow#104]
Some of the plotting functions have different variable names, even though they refer to exact same thing. For example, the parameter for starting date varies between functions and could be either of these:

- `start_date` in the function `admissions_discharges()` (see [here](https://github.com/HorridTom/hospitalflow/blob/868b676dd2af0f2a29d22276f6c3d86b20303075/R/admissions_discharges.R#L30));
- `start_dt` in the function `four_hrs_perf()` (see [here](https://github.com/HorridTom/hospitalflow/blob/868b676dd2af0f2a29d22276f6c3d86b20303075/R/four_hrs_perf.R#L19));
- `startDate` in the function `ed_occupancy_on_arrival_plot()` (see [here](https://github.com/HorridTom/hospitalflow/blob/868b676dd2af0f2a29d22276f6c3d86b20303075/R/ed_occupancy_on_arrival.R#L38));

The same goes with the parameter for data (currently `df` or `data`) - it could be renamed to reflex the type of dataset it is expecting (inpatient, emergency department, or spell). I think this is something that is worth fixing since it would make the code more consistent and reduce ambiguity.

**Comment by HorridTom** [comment]
We should definitely sort this out at some point. It will require some coordination: because this will inevitably affect many files, a branch tackling this issue should probably be the only branch open at the time. Let's discuss and decide when is a good time to do this.

**Comment by Wartynas** [comment]
Possible a duplicate of #32 ? What do you think @HorridTom ?

**Comment by Wartynas** [comment]
Solved when tidying-up.
