### ISSUE TITLE
Error when running ED_day_hour_plot

### ISSUE THREAD

**Issue by Wartynas** [HorridTom/hospitalflow#115]
This function (see [here](https://github.com/HorridTom/hospitalflow/blob/9e07907299521b2a5f6cf005813cfc680c946c8e/R/ED_day_hour.R#L55)) requires further investigation as trying to run it as follows:

```
hospitalflow::ED_day_hour_plot(
     startDay = "2019-01-01",
     endDay = "2019-01-05",
     df = ed_data,
     plot_chart = TRUE
)
```
throws an error:
```
Error: Problem with `mutate()` input `numberCode`.
x Input `numberCode` can't be recycled to size 97.
i Input `numberCode` is `1:168`.
i Input `numberCode` must be size 97 or 1, not 168.
```

**Comment by Wartynas** [comment]
Hi @ImogenConnorHelleur, have you had a chance to work with this function? Do you think it could be a duplicate of another function or a redundant one? I thought I'd ask you before trying to fix the error.

**Comment by ImogenConnorHelleur** [comment]
> Hi @ImogenConnorHelleur, have you had a chance to work with this function? Do you think it could be a duplicate of another function or a redundant one? I thought I'd ask you before trying to fix the error.

Hi @Wartynas, I'm pretty sure this is a duplicate of `occupancy_weekday_hour()` so can probably be deleted when we tidy all the folders.

**Comment by Wartynas** [comment]
Solved when tidying-up.
