### ISSUE TITLE
Make package compatible with latest version of tibble

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/hospitalflow#26]
Notably [deprecation of as.tibble](https://tibble.tidyverse.org/reference/deprecated.html)
Note warnings in tests to this effect.

This should be coordinated with #25

**Comment by Wartynas** [comment]
Hi @HorridTom, is this still an issue? There don't seem to be any warnings in tests in relation to `as.tibble`.

**Comment by HorridTom** [comment]
> Hi @HorridTom, is this still an issue? There don't seem to be any warnings in tests in relation to `as.tibble`.

@Wartynas I agree, closing this issue.
