### ISSUE TITLE
Tidy up

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/hospitalflow#46]
Remove unnecessary comments and code, refactor to DRY where needed

**Comment by HorridTom** [comment]
We should use styler! [https://style.tidyverse.org](https://style.tidyverse.org)

**Comment by HorridTom** [comment]
There are some aspects of this work that can be done within the tests, without affecting the code (e.g. applying styler to the test code); and some aspects that can be done within the R code without affecting the tests. These aspects should be kept separate i.e. do the tidying up of the tests first, and then the tidying up of the R code. There are other aspects that fundamentally require changes to both test and function files - for these, try to keep each commit limited to the changes for one function - i.e. don't mix changes for multiple functions (and their associated tests) in the same commit. I.e. there will one (or possibly more) commits for the changes associated with renaming the age - sex admissions/attendances graph.

**Comment by Wartynas** [comment]
Issues that are related to this one: #112, #104, #80, #47, #32, #27.
