### ISSUE TITLE
Check and improve documentation

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/hospitalflow#47]

**Comment by Wartynas** [comment]
Hi @HorridTom and @ImogenConnorHelleur. Alongside refactoring and renaming, I am working on the documentation of the functions as well in the tidy-up branch. I see no `#' @usage` line in the `roxygen` skeleton above the plotting functions, however, it seems that all of them have this `Usage` section in the documentation. I wanted to ask where does the `Usage` section come from after calling `?func_name`?

Changing parameter names in `#' param ...` does not update the parameter names displayed the `Usage` section.

**Comment by Wartynas** [comment]
Here is an example:
![image](https://user-images.githubusercontent.com/55479800/157512126-0790d1d3-e1e1-4060-81ed-225bff5e7973.png)

Also, note that the corresponding `.Rd` file in `man` directory has this part:

```
\usage{
admissions_discharges(
  start_date,
  end_date,
  data,
  plot_chart,
  hospital_name = "Hospital name"
)
}
```
indicating the `usage`, even though it was not specified in the `roxygen` comments. Are there any default settings made that I am not aware of?

**Comment by Wartynas** [comment]
Never mind, found the answer. :)

**Comment by Wartynas** [comment]
Solved when tidying-up.
