### ISSUE TITLE
Parallelise make_spell_table 

### ISSUE THREAD

**Issue by ImogenConnorHelleur** [HorridTom/hospitalflow#59]

**Comment by HorridTom** [comment]
@Wartynas it occurred to me yesterday that one of the first things to do here is to add new tests for the new parallelised functions, to check they return the same result as the existing functions... You can literally use the output of the current function to compare as in run both in the same function and check the results. Note that it doesn't matter if the spells are numbered differently - but it does matter that the episodes comprising each spell are the same; the test will need to reflect that.
