### ISSUE TITLE
Remove argument-free versions of analysis functions

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/hospitalflow#80]
A while back we added some functions with no arguments to call each analysis function with some preset arguments as a quick way to test the functions on a realistically-sized dataset.

This functionality would be better provided through i) example function calls on the package data (i.e. the simulated data provided as part of the package) provided in the documentation of each analysis function ii) the example report

**Comment by HorridTom** [comment]
@Wartynas I've just realised, we did have an issue for these redundant functions! This is one you could tackle in a similar way to the one we just did. No rush though, just when convenient!

**Comment by Wartynas** [comment]
Solved when tidying-up.
